#!/bin/sh
# Dell Discovery Canvas — optional Basic auth setup at container start.
#
# Reads AUTH_USERNAME and AUTH_PASSWORD env vars.
# - If both set:  generates /etc/nginx/.htpasswd with bcrypt-style MD5 (apr1)
#                 via the apache2-utils `htpasswd` binary, and writes the
#                 auth_basic directives into /etc/nginx/snippets/auth.conf
#                 so the server-scope `include` activates Basic auth.
# - If unset:     leaves the include file empty — app serves with no auth
#                 (matches the v2.2.0 default; safe for localhost-only).
#
# This script is invoked automatically by the upstream nginx:alpine
# entrypoint because it lives in /docker-entrypoint.d/ and is +x.

set -eu

SNIPPETS_DIR="/etc/nginx/snippets"
AUTH_INCLUDE="${SNIPPETS_DIR}/auth.conf"
HTPASSWD_FILE="/etc/nginx/.htpasswd"

mkdir -p "$SNIPPETS_DIR"

if [ -n "${AUTH_USERNAME:-}" ] && [ -n "${AUTH_PASSWORD:-}" ]; then
  echo "[entrypoint] Enabling Basic auth (user '${AUTH_USERNAME}')."
  if ! htpasswd -cbm "$HTPASSWD_FILE" "$AUTH_USERNAME" "$AUTH_PASSWORD" >/dev/null 2>&1; then
    echo "[entrypoint] FATAL: htpasswd failed to write ${HTPASSWD_FILE}." >&2
    exit 1
  fi
  # nginx workers run as user `nginx` in the upstream image; the file must
  # be readable by that user, not just root.
  chown nginx:nginx "$HTPASSWD_FILE"
  chmod 640 "$HTPASSWD_FILE"
  cat > "$AUTH_INCLUDE" <<EOF
# Generated by docker-entrypoint.d/40-setup-auth.sh from env vars.
auth_basic           "Dell Discovery Canvas";
auth_basic_user_file ${HTPASSWD_FILE};
EOF
elif [ -n "${AUTH_USERNAME:-}${AUTH_PASSWORD:-}" ]; then
  echo "[entrypoint] WARNING: only one of AUTH_USERNAME / AUTH_PASSWORD set — auth NOT enabled. Set both to require auth." >&2
  : > "$AUTH_INCLUDE"
else
  echo "[entrypoint] AUTH_USERNAME / AUTH_PASSWORD not set — running without auth (safe only for localhost-bound deployments)."
  : > "$AUTH_INCLUDE"
fi
